# Generated by Django 4.2.7 on 2025-12-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gitlab_url",
            field=models.URLField(blank=True),
        ),
    ]
