# Generated by Django 4.2.7 on 2025-12-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_gitlab_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='mfa_totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
