# Generated by Django 4.2.7 on 2025-12-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_mfa_enabled_profile_mfa_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mfa_totp_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
