# Generated by Django 4.2.7 on 2026-03-10 07:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(default=accounts.models._gen_verification_code, max_length=6),
        ),
    ]
