# Generated by Django 4.2.7 on 2026-03-11 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.CharField(max_length=1024)),
                ('original_filename', models.CharField(blank=True, default='', max_length=512)),
                ('mime_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_bundles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Bundle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], db_index=True, max_length=20)),
                ('account_type', models.CharField(choices=[('personal', 'Personal'), ('page', 'Page'), ('business', 'Business'), ('channel', 'Channel')], default='personal', max_length=20)),
                ('account_external_id', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_handle', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('error', 'Error')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('partial_published', 'Partial Published')], db_index=True, default='draft', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='social_hub.mediabundle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token_enc', models.TextField()),
                ('refresh_token_enc', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list)),
                ('last_refresh_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_refresh_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='social_hub.socialaccount')),
            ],
            options={
                'verbose_name': 'Social Token',
            },
        ),
        migrations.CreateModel(
            name='SocialPostTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20)),
                ('platform_post_id', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_targets', to='social_hub.socialaccount')),
                ('social_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='social_hub.socialpost')),
            ],
            options={
                'verbose_name': 'Post Target',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Audit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('impressions', models.PositiveIntegerField(blank=True, null=True)),
                ('reach', models.PositiveIntegerField(blank=True, null=True)),
                ('clicks', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('shares', models.PositiveIntegerField(blank=True, null=True)),
                ('saves', models.PositiveIntegerField(blank=True, null=True)),
                ('video_views', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='social_hub.socialposttarget')),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='MediaBundleAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_memberships', to='social_hub.mediaasset')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_assets', to='social_hub.mediabundle')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['user', 'status'], name='social_hub__user_id_70dfdb_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['status', 'scheduled_at'], name='social_hub__status_7733b1_idx'),
        ),
        migrations.AddIndex(
            model_name='socialauditlog',
            index=models.Index(fields=['user', 'action', 'created_at'], name='social_hub__user_id_66481c_idx'),
        ),
        migrations.AddIndex(
            model_name='socialauditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='social_hub__entity__bf9cb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialanalyticssnapshot',
            unique_together={('post_target', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['user', 'platform', 'status'], name='social_hub__user_id_cf925c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('user', 'platform', 'account_external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='mediabundleasset',
            unique_together={('bundle', 'asset')},
        ),
    ]
