# Generated by Django 4.2.7 on 2026-03-10 19:36

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('credits_applied', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('outstanding', 'Outstanding'), ('overdue', 'Overdue'), ('void', 'Void')], db_index=True, default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], db_index=True, default='starter', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('suspended', 'Suspended'), ('pending', 'Pending'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='member_orgs', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_orgs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('compute', 'Compute'), ('storage', 'Storage'), ('email', 'Email Delivery'), ('domain', 'Domains & DNS'), ('pipeline', 'CI/CD Pipelines'), ('networking', 'Networking'), ('monitoring', 'Monitoring'), ('auth', 'Authentication'), ('secrets', 'Secrets Management')], db_index=True, max_length=30)),
                ('unit_type', models.CharField(choices=[('vm_hour', 'VM Hour'), ('gb', 'Gigabyte'), ('email', 'Email'), ('domain', 'Domain'), ('pipeline_run', 'Pipeline Run'), ('gb_transfer', 'GB Transfer'), ('agent_hour', 'Agent Hour'), ('api_call', 'API Call'), ('key', 'Secret Key')], max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, unique=True)),
                ('service', models.CharField(choices=[('compute', 'Compute'), ('storage', 'Storage'), ('email', 'Email Delivery'), ('domain', 'Domains & DNS'), ('pipeline', 'CI/CD Pipelines'), ('networking', 'Networking'), ('monitoring', 'Monitoring'), ('auth', 'Authentication'), ('secrets', 'Secrets Management')], db_index=True, max_length=30)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('organization_id_raw', models.CharField(blank=True, max_length=120)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('units', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit_type', models.CharField(max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('event_timestamp', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='billing.organization')),
                ('pricing_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.pricingrule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Event',
                'ordering': ['-event_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('method', models.CharField(choices=[('card', 'Card'), ('wire', 'Wire Transfer'), ('ach', 'ACH'), ('crypto', 'Cryptocurrency'), ('internal', 'Internal Credit')], default='card', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.organization')),
            ],
            options={
                'verbose_name': 'Payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_charges', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total_payments', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total_credits', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('outstanding', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='billing.organization')),
            ],
            options={
                'verbose_name': 'Organization Balance',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('entry_type', models.CharField(choices=[('charge', 'Charge'), ('payment', 'Payment'), ('credit', 'Credit'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('promo', 'Promotional Credit'), ('void', 'Void'), ('writeoff', 'Write-Off')], db_index=True, max_length=20)),
                ('service', models.CharField(blank=True, db_index=True, max_length=30)),
                ('unit_type', models.CharField(blank=True, max_length=30)),
                ('units', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=16)),
                ('running_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=60)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.usageevent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='billing.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('unit_type', models.CharField(max_length=30)),
                ('units', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.invoice')),
            ],
            options={
                'ordering': ['service'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.organization'),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('credit_type', models.CharField(choices=[('credit', 'Service Credit'), ('adjustment', 'Billing Adjustment'), ('refund', 'Refund'), ('promo', 'Promotional Credit')], db_index=True, default='credit', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('applied', 'Applied'), ('expired', 'Expired'), ('void', 'Void')], db_index=True, default='active', max_length=20)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_credits', to='billing.invoice')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='billing.organization')),
            ],
            options={
                'verbose_name': 'Credit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('target', models.CharField(blank=True, max_length=300)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='info', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='billing.organization')),
            ],
            options={
                'verbose_name': 'Billing Audit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['organization', 'service', '-event_timestamp'], name='billing_usa_organiz_78caf1_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['status', '-received_at'], name='billing_usa_status_e7a548_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['service', '-event_timestamp'], name='billing_usa_service_523f19_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['service', 'is_active'], name='billing_pri_service_77f6fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricingrule',
            unique_together={('service', 'unit_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['organization', '-created_at'], name='billing_led_organiz_6a4edf_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['entry_type', '-created_at'], name='billing_led_entry_t_3d93b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['service', '-created_at'], name='billing_led_service_43dd95_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='billing_inv_organiz_63a6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='billing_inv_status_996e80_idx'),
        ),
        migrations.AddIndex(
            model_name='billingauditlog',
            index=models.Index(fields=['severity', '-created_at'], name='billing_bil_severit_2da1b9_idx'),
        ),
        migrations.AddIndex(
            model_name='billingauditlog',
            index=models.Index(fields=['action', '-created_at'], name='billing_bil_action_0cbb73_idx'),
        ),
    ]
