# Generated by Django 4.2.7 on 2025-12-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationjob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
    ]
