# Generated by Django 4.2.7 on 2025-12-29 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iot_lab', '0004_alerts_security_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_sites', to=settings.AUTH_USER_MODEL)),
                ('default_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_sites_default_for', to='iot_lab.device')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='telemetryrecord',
            options={},
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('steps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_workflow_templates', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_templates', to='iot_lab.device')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('actuator_kind', models.CharField(choices=[('gpio_write', 'GPIO Relay'), ('arduino_serial', 'Arduino Serial')], default='gpio_write', max_length=40)),
                ('actuator_config', models.JSONField(blank=True, default=dict)),
                ('soil_moisture_metric', models.CharField(blank=True, default='soil_moisture', max_length=80)),
                ('target_moisture_min', models.FloatField(blank=True, null=True)),
                ('target_moisture_max', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_zones', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_zones', to='iot_lab.device')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_zones', to='iot_lab.farmsite')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('planned_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('liters_used', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_events', to='iot_lab.devicecommand')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_events', to='iot_lab.device')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_events', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='iot_lab.irrigationzone')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='iot_lab.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_device_leases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AiInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_ai_insights', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='iot_lab.device')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='open_meteo', max_length=60)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('forecast_time', models.DateTimeField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='iot_lab.farmsite')),
            ],
            options={
                'ordering': ['-forecast_time', '-id'],
                'indexes': [models.Index(fields=['site', 'forecast_time'], name='iot_lab_wea_site_id_b67a9b_idx'), models.Index(fields=['site', 'provider', 'forecast_time'], name='iot_lab_wea_site_id_b75c8c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='irrigationzone',
            index=models.Index(fields=['site', 'is_active'], name='iot_lab_irr_site_id_b8e521_idx'),
        ),
        migrations.AddIndex(
            model_name='irrigationevent',
            index=models.Index(fields=['zone', 'requested_at'], name='iot_lab_irr_zone_id_cc0538_idx'),
        ),
        migrations.AddIndex(
            model_name='irrigationevent',
            index=models.Index(fields=['device', 'requested_at'], name='iot_lab_irr_device__f542c1_idx'),
        ),
        migrations.AddIndex(
            model_name='irrigationevent',
            index=models.Index(fields=['status', 'requested_at'], name='iot_lab_irr_status_b85b49_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelease',
            index=models.Index(fields=['device', 'ended_at', 'expires_at'], name='iot_lab_dev_device__b007c0_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelease',
            index=models.Index(fields=['user', 'ended_at', 'expires_at'], name='iot_lab_dev_user_id_8002c6_idx'),
        ),
    ]
