# Generated by Django 4.2.7 on 2025-12-29 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iot_lab', '0005_farmsite_alter_telemetryrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area_hectares', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agri_fields', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='iot_lab.farmsite')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgriNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_id', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('connectivity', models.CharField(choices=[('wifi', 'Wi‑Fi'), ('4g', '4G/LTE'), ('lorawan', 'LoRaWAN'), ('ethernet', 'Ethernet'), ('other', 'Other')], default='wifi', max_length=30)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agri_nodes', to=settings.AUTH_USER_MODEL)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agri_node', to='iot_lab.device')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='iot_lab.agrifield')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='crop_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='hardware_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='root_depth_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='iot_lab.agrifield'),
        ),
        migrations.AddField(
            model_name='irrigationzone',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='iot_lab.agrinode'),
        ),
        migrations.CreateModel(
            name='IrrigationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=dict)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('last_decision', models.CharField(blank=True, default='', max_length=40)),
                ('last_decision_reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_rules', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='iot_lab.irrigationzone')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['zone', 'enabled'], name='iot_lab_irr_zone_id_dc9230_idx'), models.Index(fields=['enabled', 'updated_at'], name='iot_lab_irr_enabled_6ef2c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgriSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('soil_moisture', 'Soil Moisture'), ('soil_temp', 'Soil Temperature'), ('air_temp_humidity', 'Air Temp/Humidity'), ('rain', 'Rain Sensor/Gauge'), ('flow_meter', 'Water Flow Meter'), ('tank_level', 'Tank Level')], max_length=40)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agri_sensors', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='iot_lab.agrinode')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='iot_lab.irrigationzone')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['node', 'kind'], name='iot_lab_agr_node_id_66c089_idx'), models.Index(fields=['zone', 'kind'], name='iot_lab_agr_zone_id_7b152d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agrinode',
            index=models.Index(fields=['field', 'updated_at'], name='iot_lab_agr_field_i_85c15f_idx'),
        ),
        migrations.AddIndex(
            model_name='agrinode',
            index=models.Index(fields=['hardware_id'], name='iot_lab_agr_hardwar_061ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='agrifield',
            index=models.Index(fields=['site', 'updated_at'], name='iot_lab_agr_site_id_76e12a_idx'),
        ),
    ]
