# Generated by Django 4.2.7 on 2025-12-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_lab', '0006_agrifield_agrinode_irrigationzone_crop_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
