# Generated by Django 4.2.7 on 2025-12-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("detailed_description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web", "Web Development"),
                            ("mobile", "Mobile Development"),
                            ("design", "Design"),
                            ("consulting", "Consulting"),
                            ("other", "Other"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                (
                    "technologies",
                    models.JSONField(
                        default=list, help_text="List of technologies used"
                    ),
                ),
                ("live_url", models.URLField(blank=True, help_text="Live project URL")),
                (
                    "github_url",
                    models.URLField(blank=True, help_text="GitHub repository URL"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/thumbnails/"
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        default=list, help_text="Additional project images"
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=200)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
