# Generated by Django 4.2.7 on 2026-03-10 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('email_type', models.CharField(choices=[('account_created', 'Account Created'), ('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('new_login', 'New Login Notification'), ('new_device_login', 'New Device / Location Login'), ('security_alert', 'Security Alert'), ('suspicious_login', 'Suspicious Login Attempt'), ('failed_logins', 'Multiple Failed Logins'), ('password_changed', 'Password Changed'), ('email_changed', 'Email Changed'), ('mfa_changed', 'MFA Enabled/Disabled'), ('role_changed', 'Role / Permission Changed'), ('incident_alert', 'Incident Alert'), ('service_outage', 'Service Outage'), ('pipeline_failure', 'Pipeline Failure'), ('degraded_performance', 'Degraded Performance'), ('billing_change', 'Billing Change'), ('payment_failed', 'Payment Failed'), ('invoice_issued', 'Invoice Issued'), ('admin_action', 'Admin Action'), ('compliance', 'Compliance Notification')], max_length=64)),
                ('template_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='sent', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_new_device', 'Login — New Device/Location'), ('logout', 'Logout'), ('password_reset_req', 'Password Reset Requested'), ('password_reset_ok', 'Password Reset Completed'), ('password_changed', 'Password Changed'), ('email_changed', 'Email Changed'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('role_assigned', 'Role Assigned'), ('role_removed', 'Role Removed'), ('account_suspended', 'Account Suspended'), ('account_activated', 'Account Activated'), ('api_key_created', 'API Key Created'), ('api_key_revoked', 'API Key Revoked'), ('ip_blocked', 'IP Address Blocked'), ('admin_action', 'Admin Action'), ('incident_triggered', 'Incident Triggered')], max_length=64)),
                ('target_email', models.EmailField(blank=True, default='', max_length=254)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('email_log', models.ForeignKey(blank=True, help_text='Email sent as a result of this event (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='emails.emaillog')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Audit Log',
                'verbose_name_plural': 'Security Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient', 'created_at'], name='emails_emai_recipie_d91a99_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email_type', 'created_at'], name='emails_emai_email_t_10931c_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', 'created_at'], name='emails_emai_status_0b5614_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['action', 'created_at'], name='emails_secu_action_71a283_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['actor', 'created_at'], name='emails_secu_actor_i_8e7703_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['ip_address', 'created_at'], name='emails_secu_ip_addr_667948_idx'),
        ),
    ]
