# Generated by Django 4.2.7 on 2026-03-10 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, default='', help_text='Override template subject if set', max_length=255)),
                ('recipients', models.JSONField(blank=True, default=list, help_text='List of email strings or {email,name} dicts')),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('bounce_count', models.PositiveIntegerField(default=0)),
                ('unsubscribe_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SenderIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('usage', models.CharField(choices=[('transactional', 'Transactional (auth, security, system)'), ('marketing', 'Marketing (campaigns, newsletters, promos)'), ('both', 'Both')], default='transactional', max_length=16)),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254)),
                ('spf_verified', models.BooleanField(default=False)),
                ('dkim_verified', models.BooleanField(default=False)),
                ('dmarc_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sender Identity',
                'verbose_name_plural': 'Sender Identities',
                'ordering': ['domain', 'email'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(help_text='Short slug, e.g. TMPL-01', max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('system', 'System (Default)'), ('security', 'Security'), ('notification', 'Notification'), ('marketing', 'Marketing'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('permission', models.CharField(choices=[('global', 'Global — visible to all users'), ('personal', 'Personal — creator only'), ('marketing', 'Marketing — marketing team')], default='global', max_length=16)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField(help_text='HTML source; use {{variable}} placeholders')),
                ('text_body', models.TextField(blank=True, default='', help_text='Plain-text fallback')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variable names, e.g. ["name","link","date"]')),
                ('preview_text', models.CharField(blank=True, default='', max_length=200)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates_edited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('unsubscribed', 'Unsubscribed')], default='queued', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='emails.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Log',
                'verbose_name_plural': 'Campaign Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='sender_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='emails.senderidentity'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='emails.emailtemplate'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['category', 'is_active'], name='emails_emai_categor_773b97_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['permission', 'created_by'], name='emails_emai_permiss_2372ce_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlog',
            index=models.Index(fields=['campaign', 'status'], name='emails_camp_campaig_860c71_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlog',
            index=models.Index(fields=['recipient', 'created_at'], name='emails_camp_recipie_7f1aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'created_at'], name='emails_camp_status_fb11fd_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['scheduled_at'], name='emails_camp_schedul_ae0404_idx'),
        ),
    ]
