# Generated by Django 4.2.7 on 2026-03-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_campaign_senderidentity_emailtemplate_campaignlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=255)),
                ('to_email', models.CharField(max_length=512)),
                ('cc', models.TextField(blank=True, default='')),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=512)),
                ('subject', models.CharField(blank=True, default='(no subject)', max_length=998)),
                ('html_body', models.TextField(blank=True, default='')),
                ('text_body', models.TextField(blank=True, default='')),
                ('preview_text', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived'), ('spam', 'Spam')], default='unread', max_length=16)),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Full raw webhook payload for debugging')),
                ('spam_score', models.FloatField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, help_text='Date header from the email itself', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inbound Email',
                'verbose_name_plural': 'Inbound Emails',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='emails_inbo_status_ee4e51_idx'), models.Index(fields=['from_email', 'created_at'], name='emails_inbo_from_em_9ae48c_idx'), models.Index(fields=['message_id'], name='emails_inbo_message_5ff5ef_idx')],
            },
        ),
    ]
