# Generated by Django 4.2.7 on 2025-12-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='activity_ac_created_95aa6e_idx',
            old_name='activity_ev_created_0cfa1b_idx',
        ),
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='activity_ac_action_b077a4_idx',
            old_name='activity_ev_action_c8b6a6_idx',
        ),
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='activity_ac_path_1f96fc_idx',
            old_name='activity_ev_path_5e6db8_idx',
        ),
    ]
