# Generated by Django 5.2.9 on 2025-12-09 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("excerpt", models.TextField(max_length=500)),
                ("content", models.TextField()),
                ("author", models.CharField(default="Samuel Realm", max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cloud", "Cloud Architecture"),
                            ("ai", "AI & Machine Learning"),
                            ("devops", "DevOps"),
                            ("infrastructure", "Infrastructure"),
                            ("security", "Security"),
                            ("tutorial", "Tutorial"),
                        ],
                        default="tutorial",
                        max_length=50,
                    ),
                ),
                ("featured_image", models.URLField(blank=True, null=True)),
                (
                    "tags",
                    models.CharField(help_text="Comma-separated tags", max_length=200),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "read_time",
                    models.IntegerField(
                        default=5, help_text="Estimated read time in minutes"
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
