# Generated by Django 4.2.7 on 2025-12-06 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Brief summary of the post", max_length=300
                    ),
                ),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai", "Artificial Intelligence"),
                            ("bigdata", "Big Data"),
                            ("robotics", "Robotics"),
                            ("cloud", "Cloud Computing"),
                            ("devops", "DevOps"),
                            ("cybersecurity", "Cybersecurity"),
                            ("blockchain", "Blockchain"),
                            ("iot", "Internet of Things"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
                ("featured_image", models.URLField(blank=True, null=True)),
                ("published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
