# Generated by Django 4.2.7 on 2025-12-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='atonixdev', max_length=100),
        ),
    ]
