# Generated by Django 4.2.7 on 2026-03-11 11:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='finance.department')),
            ],
            options={
                'verbose_name': 'Department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Review')], db_index=True, default='active', max_length=20)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100, higher = more risk')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='finance.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Contract',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('fiscal_year', models.IntegerField(db_index=True)),
                ('scenario', models.CharField(choices=[('baseline', 'Baseline'), ('optimistic', 'Optimistic'), ('pessimistic', 'Pessimistic'), ('stretch', 'Stretch')], default='baseline', max_length=20)),
                ('projected_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('projected_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('projected_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('assumptions', models.TextField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forecast',
                'ordering': ['-fiscal_year', 'scenario'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(db_index=True, default='USD', max_length=3)),
                ('target_currency', models.CharField(db_index=True, max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=16)),
                ('effective_date', models.DateField(db_index=True)),
                ('source', models.CharField(default='manual', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'ordering': ['-effective_date'],
                'unique_together': {('base_currency', 'target_currency', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_procurements', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to='finance.department')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to='finance.vendor')),
            ],
            options={
                'verbose_name': 'Procurement Request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='finance_pro_status_113155_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('budget', 'Budget'), ('forecast', 'Forecast'), ('department', 'Department'), ('vendor', 'Vendor'), ('procurement', 'Procurement'), ('compliance', 'Compliance'), ('currency', 'Currency'), ('reconciliation', 'Reconciliation')], db_index=True, max_length=20)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('target', models.CharField(blank=True, max_length=300)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', max_length=10)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Audit Log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', '-created_at'], name='finance_fin_categor_c22dc6_idx'), models.Index(fields=['severity', '-created_at'], name='finance_fin_severit_4c2920_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('payroll', 'Payroll'), ('cloud', 'Cloud Infrastructure'), ('software', 'Software Licenses'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('support', 'Support'), ('travel', 'Travel'), ('equipment', 'Equipment'), ('consulting', 'Consulting'), ('other', 'Other')], db_index=True, max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.department')),
            ],
            options={
                'verbose_name': 'Department Expense',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['department', 'category', '-period_start'], name='finance_dep_departm_db70db_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('framework', models.CharField(choices=[('pci_dss', 'PCI-DSS'), ('soc2', 'SOC 2'), ('gdpr', 'GDPR'), ('popia', 'POPIA'), ('internal', 'Internal Policy')], db_index=True, max_length=20)),
                ('check_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('in_review', 'In Review'), ('remediation', 'Remediation')], db_index=True, default='in_review', max_length=20)),
                ('risk_level', models.IntegerField(default=0, help_text='0-100 risk score')),
                ('findings', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Check',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['framework', 'status'], name='finance_com_framewo_87c23f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('fiscal_year', models.IntegerField(db_index=True)),
                ('period', models.CharField(choices=[('annual', 'Annual'), ('q1', 'Q1'), ('q2', 'Q2'), ('q3', 'Q3'), ('q4', 'Q4'), ('monthly', 'Monthly')], default='annual', max_length=10)),
                ('allocated', models.DecimalField(decimal_places=2, help_text='Total budget allocated', max_digits=16)),
                ('spent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount spent so far', max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.department')),
            ],
            options={
                'verbose_name': 'Budget',
                'ordering': ['-fiscal_year', 'period'],
                'indexes': [models.Index(fields=['fiscal_year', 'status'], name='finance_bud_fiscal__8128ed_idx')],
            },
        ),
    ]
