# Generated by Django 4.2.7 on 2025-12-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                (
                    "client_title",
                    models.CharField(
                        blank=True, help_text="e.g., CEO at Company", max_length=200
                    ),
                ),
                ("client_company", models.CharField(blank=True, max_length=200)),
                (
                    "client_avatar",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("content", models.TextField(help_text="Testimonial text")),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, help_text="Associated project", max_length=200
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
