# Generated by Django 4.2.7 on 2026-03-11 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('token_type', models.CharField(choices=[('color', 'Color Token'), ('font', 'Font Family'), ('spacing', 'Spacing Unit'), ('asset', 'Brand Asset')], db_index=True, max_length=10)),
                ('value', models.CharField(help_text='CSS value, URL, or token value', max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Token',
                'ordering': ['token_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('investor', 'Investor'), ('advisor', 'Advisor'), ('board_member', 'Board Member'), ('partner', 'Partner')], db_index=True, default='investor', max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('investment', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stakeholder',
                'ordering': ['-investment', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('compute', 'Compute Instance'), ('storage', 'Storage Volume'), ('database', 'Database'), ('container', 'Container Registry'), ('domain', 'Domain'), ('other', 'Other')], db_index=True, max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('provisioning', 'Provisioning'), ('decommissioned', 'Decommissioned')], db_index=True, default='active', max_length=20)),
                ('storage_quota', models.CharField(blank=True, help_text='e.g. 100GB', max_length=30)),
                ('region', models.CharField(blank=True, max_length=60)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Allocation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', max_length=10)),
                ('module', models.CharField(blank=True, db_index=True, max_length=60)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portal Audit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('doc_type', models.CharField(choices=[('pitch_deck', 'Pitch Deck'), ('compliance', 'Compliance Document'), ('financial_report', 'Financial Report'), ('legal', 'Legal Agreement'), ('update', 'Investor Update'), ('other', 'Other')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True, max_length=600)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('confidential', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor Document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FounderDirective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(help_text='Markdown content')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], db_index=True, default='normal', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft')], db_index=True, default='active', max_length=10)),
                ('pinned', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Founder Directive',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CulturalGuideline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('category', models.CharField(db_index=True, default='general', max_length=60)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cultural Guideline',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
    ]
