# Generated by Django 4.2.7 on 2026-03-11 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('founder_portal', '0002_campaign_designstandard_integrationconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Short code e.g. EXC, BRD', max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url_path', models.CharField(help_text='Frontend route e.g. /founder-portal/investor', max_length=300)),
                ('category', models.CharField(choices=[('founder', 'Founder Portal'), ('finance', 'Finance & Billing'), ('operations', 'Operations'), ('admin', 'Administration'), ('product', 'Product'), ('public', 'Public')], db_index=True, default='founder', max_length=15)),
                ('default_access', models.CharField(choices=[('founder', 'Founder Only'), ('staff', 'Staff'), ('any_auth', 'Any Authenticated'), ('public', 'Public')], db_index=True, default='staff', max_length=10)),
                ('accent_color', models.CharField(default='#A81D37', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Registry',
                'verbose_name_plural': 'Dashboard Registry',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('admin', 'Admin')], default='view', max_length=6)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='founder_portal.dashboardregistry')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Permission',
                'ordering': ['-granted_at'],
                'unique_together': {('dashboard', 'user')},
            },
        ),
    ]
